DROP TABLE IF EXISTS job_docker;
DROP TABLE IF EXISTS job_machine;
DROP TABLE IF EXISTS job CASCADE;
DROP TABLE IF EXISTS workflow CASCADE;
DROP TRIGGER set_timestamp ON pipeline CASCADE;
DROP TABLE IF EXISTS pipeline CASCADE;